---
title: "Average Age of Congress Freshmen"
author: "Evelyn Cai"
date: "April 7, 2019"
output: html_document
---

```{r setup, include=FALSE}
# Load appropriate libraries
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(ggplot2)
library(fivethirtyeight)
library(ggthemes)
data("congress_age")
```


```{r message=FALSE, echo=FALSE}

congress_age %>%
  # Create new column variable for congressional year
  mutate(year = 1787 + 2*(congress)) %>%
  # Filter for only Democratic and Republican parties
  filter(party %in% c("D", "R"),
         # Filter for newcomers to Congress
         incumbent == "FALSE") %>%
  # Display values based on party and year
  group_by(year, party) %>%
  # Calculate and create new column variable for average age
  summarize(avg_age = mean(age)) %>%

# Create a line plot mapping average age over time with a differently colored line for each party
ggplot(mapping = aes(x = year, y = avg_age, color = party)) +
  # Hide legend
  geom_line(show.legend = FALSE, size = 1.25) +
  # Add title, subtitle and caption
  labs(title = "Average Age of New Members of Congress",
       subtitle = "Rolling two-term average at start of term, 1949-2013",
       caption = "SOURCE: GOVTRACK, THE NEW YORK TIMES, THE SUNLIGHT FOUNDATION") +
  # Add labels to each line
  annotate("text", x = 1997, y = 50.75, size = 5, 
           color = "#008FD5", family = "sans", label = "Democrats") + 
  annotate("text", x = 1960, y = 50.75, size = 5, 
           color = "#FF2700", family = "sans", label = "Republicans") +
  # Add x- and y- axis labels
  scale_x_continuous(breaks = seq(1950, 2010, by = 10),
                     label = c("1950", "'60", "'70", "'80",
                               "'90", "2000", "'10")) +
  scale_y_continuous(breaks = seq(40, 60, by = 5),
                     label = c("40", "45", "50", "55", "60 yrs")) +
  # Include lower year of 1950 and upper ages of 60
  expand_limits(y = 60, x = 1950) +
  # Use FiveThirtyEight's themes and colors
  scale_color_fivethirtyeight() +
  theme_fivethirtyeight()
```